spring:
  datasource:
    url: ${DATABASE_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driverClassName: org.postgresql.Driver
  jpa:
    hibernate.ddl-auto: create
    show-sql: false
    properties.hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
