spring:
  datasource:
    url: jdbc:sqlserver://alotta-db.database.windows.net:1433;database=alotta-db;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;
    username: alotta-admin@alotta-db
    password: lucapston2023!
    database: alotta-db
    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    hibernate.ddl-auto: update
    show-sql: false
    properties.hibernate.dialect: org.hibernate.dialect.SQLServer2012Dialect
