spring:
  datasource:
    url: ${DATABASE_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driverClassName: org.postgresql.Driver
  jpa:
    hibernate.ddl-auto: create
    show-sql: false
    properties.hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect

alotta-properties:
  backendUrl: https://alotta-backend.herokuapp.com/
  qrApiUrl: https://api.qr-code-generator.com/v1/create?access-token=
  qrApiToken: OYxLPbO9S7Yrky8zH81G7jsBwzPF-mgORANb4D4Va3xgqj9PZUm3RyaK3rvGMEYG

qr-code-properties:
  frameName: no-frame
  imageWidth: 400
  imageHeight: 400
  imageFormat: PNG
  backgroundColor: "#f8f4eb"
  foregroundColor: "#eb7450"
  markerColor: "#4d9f6b"
  markerTemplate: version13
