spring:
  datasource:
    url: jdbc:sqlserver://alotta-db.database.windows.net:1433;database=alotta-db;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;createDatabaseIfNotExist=true;
    username: alotta-admin@alotta-db
    password: lucapston2023!
    database: alotta-db
    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    hibernate.ddl-auto: update
    show-sql: true
    properties.hibernate.dialect: org.hibernate.dialect.SQLServer2012Dialect

alotta-properties:
  backendUrl: http://alotta-spring-app.azurewebsites.net
  qrApiUrl: https://api.qr-code-generator.com/v1/create?access-token=
  qrApiToken: OYxLPbO9S7Yrky8zH81G7jsBwzPF-mgORANb4D4Va3xgqj9PZUm3RyaK3rvGMEYG

qr-code-properties:
  frameName: no-frame
  imageWidth: 800
  imageHeight: 800
  imageFormat: PNG
  backgroundColor: "#FFFFFF"
  foregroundColor: "#eb7450"
  markerColor: "#4d9f6b"
  markerTemplate: version13