DROP TABLE Coupon;
CREATE TABLE Coupon (
    CouponId NUMBER GENERATED BY DEFAULT AS IDENTITY,
    CouponType VARCHAR(255),
    PercentageOff FLOAT,
    DollarsOff FLOAT,
    CouponInfo VARCHAR(255),
    FoodCategories VARCHAR(255),
    NumberOfCouponsPerCustomer FLOAT,
    TotalNumberOfCoupons FLOAT,
    NumberOfCouponsSold FLOAT,
    PRIMARY KEY(CouponId)
    
);