DROP ALL OBJECTS;

CREATE TABLE Coupon (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    coupon_type VARCHAR(255),
    percentage_off FLOAT,
    dollars_off FLOAT,
    coupon_info VARCHAR(255),
    food_categories VARCHAR(255),
    number_of_coupons_per_customer FLOAT,
    total_number_of_coupons FLOAT,
    number_of_coupons_sold FLOAT,
    PRIMARY KEY(id)
);