DROP ALL OBJECTS;

CREATE TABLE Coupon (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    title VARCHAR(255),
    coupon_type VARCHAR(255),
    percentage_off FLOAT,
    dollars_off FLOAT,
    coupon_info VARCHAR(255),
    food_categories VARCHAR(255),
    number_of_coupons_per_customer FLOAT,
    total_number_of_coupons FLOAT,
    number_of_coupons_sold FLOAT,
    start_date DATETIME,
    end_date DATETIME,
    PRIMARY KEY(id)
);


CREATE TABLE Customer (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    Username VARCHAR(15) NOT NULL,
    Password VARCHAR(15) NOT NULL,
    Account_Type VARCHAR(25) NOT NULL,
    First_Name VARCHAR(15) NOT NULL,
    Last_Name VARCHAR(15) NOT NULL,
    Email VARCHAR(30) NOT NULL,
    Phone_Number VARCHAR(15) NOT NULL,
    Zipcode VARCHAR(5) NOT NULL,
    PRIMARY KEY(id)
);

CREATE TABLE Customer_Inventory (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    coupon_id NUMBER,
    customer_id NUMBER,
    redeemed BOOLEAN,
    PRIMARY KEY(id),
    FOREIGN KEY (coupon_id) REFERENCES Coupon(id),
    FOREIGN KEY (customer_id) REFERENCES Customer(id)
);