DROP ALL OBJECTS;

CREATE TABLE Coupon (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    title VARCHAR(255),
    coupon_type VARCHAR(255),
    percentage_off FLOAT,
    dollars_off FLOAT,
    coupon_info VARCHAR(255),
    food_categories VARCHAR(255),
    number_of_coupons_per_customer FLOAT,
    total_number_of_coupons FLOAT,
    number_of_coupons_sold FLOAT,
    start_date DATETIME,
    end_date DATETIME,
    PRIMARY KEY(id)
);


CREATE TABLE Restaurant (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(255) NOT NULL,
    phone_number VARCHAR(15) NOT NULL,
    about_me VARCHAR(255),
    food_categories VARCHAR(255),
    email VARCHAR(30),
    logo BLOB,
    max_catering_size_per_person NUMBER,
    minimum_notice FLOAT,
    zip_code char(5),
    PRIMARY KEY(id)
);

CREATE TABLE Restaurant_Inventory (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    coupon_id NUMBER,
    restaurant_id NUMBER,
    start_date DATETIME,
    end_date DATETIME,
    PRIMARY KEY(id),
    FOREIGN KEY (coupon_id) REFERENCES Coupon(id),
    FOREIGN KEY (restaurant_id) REFERENCES Restaurant(id)
);