DROP TABLE Restaurant;
CREATE TABLE Restaurant (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(255) NOT NULL,
    phone_number VARCHAR(15) NOT NULL,
    about_me VARCHAR(255),
    food_categories VARCHAR(255),
    email VARCHAR(30),
    logo BLOB,
    max_catering_size_per_person NUMBER,
    minimum_notice FLOAT,
    zip_code char(5),
    PRIMARY KEY(id)
);