DROP ALL OBJECTS;

CREATE TABLE AppUser (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    Username VARCHAR(15) NOT NULL,
    Password VARCHAR(15) NOT NULL,
    Account_Type VARCHAR(25) NOT NULL,
    First_Name VARCHAR(15) NOT NULL,
    Last_Name VARCHAR(15) NOT NULL,
    Email VARCHAR(30) NOT NULL,
    Phone_Number VARCHAR(15) NOT NULL,
    Zipcode VARCHAR(5) NOT NULL,
    PRIMARY KEY(id)
);

CREATE TABLE Restaurant (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(255) NOT NULL,
    phone_number VARCHAR(15) NOT NULL,
    about_me VARCHAR(255),
    food_categories VARCHAR(255),
    email VARCHAR(30),
    logo BLOB,
    max_catering_size_per_person NUMBER,
    minimum_notice FLOAT,
    zip_code char(5),
    PRIMARY KEY(id)
);

CREATE TABLE User_Restaurant (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    appuser_id NUMBER,
    restaurant_id NUMBER,
    PRIMARY KEY(id),
    FOREIGN KEY (appuser_id) REFERENCES AppUser(id),
    FOREIGN KEY (restaurant_id) REFERENCES Restaurant(id)
);
